### ISSUE TITLE
Missing .ply Files in Avatar Dataset: Discrepancy Between frame_list.csv and registration_vertices.zip

### ISSUE THREAD

**Issue by lskdream** [facebookresearch/ava-256#21]
Hi!

I've noticed a discrepancy in the dataset. There are 5,022 rows listed in the frame_list.csv file under the 20230324--0820--AEY864/decoder/ folder. However, there are only 5,001 files in the 20230324--0820--AEY864/decoder/kinematic_tracking/registration_vertices.zip. It appears that some .ply files are missing. Could you please help resolve this issue?

Thanks!

**Comment by una-dinosauria** [comment]
Some assets and images are expected to be missing. Our dataloader accounts for this. We do not have plans to fill these gaps.
