### ISSUE TITLE
Difference between difference sizes of datasets

### ISSUE THREAD

**Issue by chaitanya100100** [facebookresearch/ava-256#9]
Hello,
Thanks for releasing this data and code.
According to [data](https://github.com/facebookresearch/ava-256?tab=readme-ov-file#data) section of the readme, we can download dataset in different sizes (4 to 32TB). However, it is not clear if the smaller dataset has less subjects, or less number of frames, or low quality of images. Can you give some information on what is the difference between these dataset sizes?
Thanks.

**Comment by una-dinosauria** [comment]
Sorry, can't believe I missed this.

| size | fps | resolution | frames per subject | avif quality |
| --- | --- | --- | --- | --- |
| 4 TB | 7.5 | 1024 x 667 | 5 000 | 63 |
| 4 TB | 7.5 | 1024 x 667 | 5 000 | 63 |
| 4 TB | 7.5 | 1024 x 667 | 5 000 | 63 |

**Comment by chaitanya100100** [comment]
Thanks! This is really useful.
